### ISSUE TITLE
Issue using the Docker Container

### ISSUE THREAD

**Issue by TheFonix** [tellform/tellform#219]
#### What's this issue about?
Docker container being unusable

#### Expected behavior
The page should load successfully without any issues. Once the login page has been successfully passed

#### Actual behavior
Once logged in the container seem to spam 
```
GET /forms 401 1.060 ms - 12
```
Unsure as to what is causing the 401 as the login seemed successful 
#### Steps to reproduce
Run the docker setup from the main Tellform docker deployment page & visit the online page. Once logged in try to create a new form, this won't work as the page seems to keep redirecting back & forth from `/signin` to `/forms`

#### Environment
Docker is `Docker version 17.03.1-ce, build c6d412e`
Running on Ubuntu 16.04 (Fresh Install)

**Comment by whitef0x0** [comment]
@TheFonix have you set the BASE_URL to the domain you are using to access your TellForm instance?

**Comment by James9074** [comment]
@whitef0x0 I noticed two things with the Dockerfile: 
- That env vars set are overwritten with the .env file included with the image build (which is bad practice, the image isn't very reusable at that point, and I have to build the container with my creds hardcoded in which _isn't secure at all_).
- That [process.yml](https://github.com/tellform/tellform/blob/master/Dockerfile-production#L69) isn't being included in the image at all, meaning you have to start it with npm start (we should either include it or change the cmd to ["npm", "start"], your pick.

What your thoughts are here on that? I've got to change it for another project, so I can submit a PR, just need to know what you'd prefer for these.

**Comment by whitef0x0** [comment]
@James9074 I agree that the .env files shouldn't be in the docker image. Maybe we should move to something using docker-compose instead as the default for using TellForm with docker (see [this]( https://www.ctl.io/developers/blog/post/tutorial-protecting-sensitive-info-docker) article for more in-depth look)

About pm2, I agree that we should probably include the process.yml file in the image to avoid having to use npm start.

**Comment by James9074** [comment]
@whitef0x0 Perfect, I'll throw a PR up later this week with some docker enhancements then. I use docker-compose for about everything I do these days (_...and I happen to work in infosec securing containers day to day_).

If you really get into it, you'll want to use [secrets](http://rancher.com/docs/rancher/v1.6/en/cattle/secrets/) and secrets management tools like [Vault](https://www.vaultproject.io/). That's not something the app handles though, it's entirely up to the user to implement - we just need to make sure they have the ability to load up their own env vars on container creation instead of build.

On a side note, I'm going to take a crack at making that BASE_URL semi-automatically determined if it's not set, looks like it's the source of all evil for a lot of users hah.

**Comment by whitef0x0** [comment]
@James9074 Fixing the BASE_URL is a bucket list item for me, just haven't had time to get around to it.

A fix to it would be greatly appreciated! (I could send some stickers your way if you end up doing it).

**Comment by leonardloo** [comment]
Could I ask a question - do we have to run `npm install` locally before building the docker image in production? I realise that if I don't I'm getting `angular not found` errors.

**Comment by James9074** [comment]
Bower install is the missing command for docker builds. It provides the
front end libraries.

**Comment by leonardloo** [comment]
@James9074 Does this mean I should run `bower install` first then build from the Dockerfile-production?

**Comment by James9074** [comment]
@leonardloo Yup, you'll want to bower install and then docker build, which will copy the front end libraries into the container. Alternatively you can add bower to the dockerfile and install them there (useful if you're doing CI).

**Comment by whitef0x0** [comment]
@James9074 I should probably fix this

**Comment by James9074** [comment]
Pretty sure `RUN bower install` in the Docekrfile will do the job there, I just haven't had a chance to test that myself.

**Comment by whitef0x0** [comment]
@James9074 this should not be an issue though, as the postinstall for npm install run bower install (see line 23 here https://github.com/tellform/tellform/blob/master/package.json)

**Comment by whitef0x0** [comment]
@James9074 seems like the issue might be related to this https://github.com/nodejs/docker-node/issues/185

**Comment by James9074** [comment]
Hmm, I'll take a look this weekend and see what's going on maybe set up
auto builds for docker hub as well

**Comment by whitef0x0** [comment]
@James9074 Cool. I can give you admin access to the tellform docker hub account if you need it. Just email me your docker hub username to team at tellform.com

**Comment by vamsipkris** [comment]
I cannot even login/signup using the docker image. I have followed the instructions written [here](https://www.tellform.com/selfhosted), and I get the following errors

Couldn't complete registration due to errors:
[object Object]

Could you please let me know how to fix this, and signup and login? I have used the following command for starting the docker 

docker run --rm -p 3000:3000 --link someredis:redis-db --link somemongo:db -e "SUBDOMAINS_DISABLED=TRUE" -e "DISABLE_CLUSTER_MODE=TRUE" -e "MAILER_EMAIL_ID=" -e "MAILER_FROM=" -e "MAILER_SERVICE_PROVIDER=" -e "MAILER_PASSWORD=" -e "BASE_URL=localhost" -e "NODE_ENV=development" -p 80:80 tellform/development

**Comment by alexsegura** [comment]
Hi, not sure this is related, but Docker image on Docker Hub looks old (last updated 9 months ago): for example it doesn't contain the `create_admin.js` script.
Could you please update the image on Docker Hub?

I tried this is `docker-compose.yml` to build the latest image with no luck (I commented the line which copies `.env` file)

```
tellform:
    # image: tellform/development
    build: https://github.com/alexsegura/tellform.git#noenv
```

**Comment by whitef0x0** [comment]
@vamsipkris you need to add a valid SMTP service and change MAILER_PASSWORD, MAILER_EMAIL_ID and MAILER_FROM to get it to work
